// Language registry generated from CodeMirror 5's `mode/meta.js`
// (codemirror@5.65.21, MIT) and mapped onto `@codemirror/legacy-modes`
// modules. `module` is the legacy-modes mode module, `export` the named
// export holding the StreamParser.
// Regenerate with `node workspace/src/gen-code-funcs-modes.js` (wrapper repo).

export interface Mode {
  name: string;
  module: string;
  export: string;
  alias?: string[];
  ext?: string[];
}

export const modeInfo: Mode[] = [
  { name: 'APL', module: 'apl', export: 'apl', ext: ['dyalog', 'apl'] },
  {
    name: 'PGP',
    module: 'asciiarmor',
    export: 'asciiArmor',
    ext: ['asc', 'pgp', 'sig'],
  },
  { name: 'ASN.1', module: 'asn1', export: 'asn1', ext: ['asn', 'asn1'] },
  { name: 'Asterisk', module: 'asterisk', export: 'asterisk' },
  {
    name: 'Brainfuck',
    module: 'brainfuck',
    export: 'brainfuck',
    ext: ['b', 'bf'],
  },
  { name: 'C', module: 'clike', export: 'c', ext: ['c', 'h', 'ino'] },
  {
    name: 'C++',
    module: 'clike',
    export: 'cpp',
    alias: ['cpp'],
    ext: ['cpp', 'c++', 'cc', 'cxx', 'hpp', 'h++', 'hh', 'hxx'],
  },
  {
    name: 'Cobol',
    module: 'cobol',
    export: 'cobol',
    ext: ['cob', 'cpy', 'cbl'],
  },
  {
    name: 'C#',
    module: 'clike',
    export: 'csharp',
    alias: ['csharp', 'cs'],
    ext: ['cs'],
  },
  {
    name: 'Clojure',
    module: 'clojure',
    export: 'clojure',
    ext: ['clj', 'cljc', 'cljx'],
  },
  {
    name: 'ClojureScript',
    module: 'clojure',
    export: 'clojure',
    ext: ['cljs'],
  },
  {
    name: 'Closure Stylesheets (GSS)',
    module: 'css',
    export: 'gss',
    ext: ['gss'],
  },
  {
    name: 'CMake',
    module: 'cmake',
    export: 'cmake',
    ext: ['cmake', 'cmake.in'],
  },
  {
    name: 'CoffeeScript',
    module: 'coffeescript',
    export: 'coffeeScript',
    alias: ['coffee', 'coffee-script'],
    ext: ['coffee'],
  },
  {
    name: 'Common Lisp',
    module: 'commonlisp',
    export: 'commonLisp',
    alias: ['lisp'],
    ext: ['cl', 'lisp', 'el'],
  },
  {
    name: 'Cypher',
    module: 'cypher',
    export: 'cypher',
    ext: ['cyp', 'cypher'],
  },
  {
    name: 'Cython',
    module: 'python',
    export: 'cython',
    ext: ['pyx', 'pxd', 'pxi'],
  },
  { name: 'Crystal', module: 'crystal', export: 'crystal', ext: ['cr'] },
  { name: 'CSS', module: 'css', export: 'css', ext: ['css'] },
  { name: 'CQL', module: 'sql', export: 'cassandra', ext: ['cql'] },
  { name: 'D', module: 'd', export: 'd', ext: ['d'] },
  { name: 'Dart', module: 'dart', export: 'dart', ext: ['dart'] },
  { name: 'diff', module: 'diff', export: 'diff', ext: ['diff', 'patch'] },
  { name: 'Dockerfile', module: 'dockerfile', export: 'dockerFile' },
  { name: 'DTD', module: 'dtd', export: 'dtd', ext: ['dtd'] },
  {
    name: 'Dylan',
    module: 'dylan',
    export: 'dylan',
    ext: ['dylan', 'dyl', 'intr'],
  },
  { name: 'EBNF', module: 'ebnf', export: 'ebnf' },
  { name: 'ECL', module: 'ecl', export: 'ecl', ext: ['ecl'] },
  { name: 'edn', module: 'clojure', export: 'clojure', ext: ['edn'] },
  { name: 'Eiffel', module: 'eiffel', export: 'eiffel', ext: ['e'] },
  { name: 'Elm', module: 'elm', export: 'elm', ext: ['elm'] },
  { name: 'Erlang', module: 'erlang', export: 'erlang', ext: ['erl'] },
  { name: 'Esper', module: 'sql', export: 'esper' },
  { name: 'Factor', module: 'factor', export: 'factor', ext: ['factor'] },
  { name: 'FCL', module: 'fcl', export: 'fcl' },
  {
    name: 'Forth',
    module: 'forth',
    export: 'forth',
    ext: ['forth', 'fth', '4th'],
  },
  {
    name: 'Fortran',
    module: 'fortran',
    export: 'fortran',
    ext: ['f', 'for', 'f77', 'f90', 'f95'],
  },
  {
    name: 'F#',
    module: 'mllike',
    export: 'fSharp',
    alias: ['fsharp'],
    ext: ['fs'],
  },
  { name: 'Gas', module: 'gas', export: 'gas', ext: ['s'] },
  { name: 'Gherkin', module: 'gherkin', export: 'gherkin', ext: ['feature'] },
  { name: 'Go', module: 'go', export: 'go', ext: ['go'] },
  {
    name: 'Groovy',
    module: 'groovy',
    export: 'groovy',
    ext: ['groovy', 'gradle'],
  },
  { name: 'Haskell', module: 'haskell', export: 'haskell', ext: ['hs'] },
  { name: 'Haxe', module: 'haxe', export: 'haxe', ext: ['hx'] },
  { name: 'HXML', module: 'haxe', export: 'hxml', ext: ['hxml'] },
  {
    name: 'HTML',
    module: 'htmlmixed',
    export: 'html',
    alias: ['xhtml'],
    ext: ['html', 'htm', 'handlebars', 'hbs'],
  },
  { name: 'HTTP', module: 'http', export: 'http' },
  { name: 'IDL', module: 'idl', export: 'idl', ext: ['pro'] },
  {
    name: 'Pug',
    module: 'pug',
    export: 'pug',
    alias: ['jade'],
    ext: ['jade', 'pug'],
  },
  { name: 'Java', module: 'clike', export: 'java', ext: ['java'] },
  {
    name: 'JavaScript',
    module: 'javascript',
    export: 'javascript',
    alias: ['ecmascript', 'js', 'node'],
    ext: ['js'],
  },
  {
    name: 'JSON',
    module: 'javascript',
    export: 'json',
    alias: ['json5'],
    ext: ['json', 'map'],
  },
  {
    name: 'JSON-LD',
    module: 'javascript',
    export: 'jsonld',
    alias: ['jsonld'],
    ext: ['jsonld'],
  },
  { name: 'JSX', module: 'javascript', export: 'javascript', ext: ['jsx'] },
  {
    name: 'Jinja2',
    module: 'jinja2',
    export: 'jinja2',
    ext: ['j2', 'jinja', 'jinja2'],
  },
  {
    name: 'Julia',
    module: 'julia',
    export: 'julia',
    alias: ['jl'],
    ext: ['jl'],
  },
  { name: 'Kotlin', module: 'clike', export: 'kotlin', ext: ['kt'] },
  { name: 'LESS', module: 'css', export: 'less', ext: ['less'] },
  {
    name: 'LiveScript',
    module: 'livescript',
    export: 'liveScript',
    alias: ['ls'],
    ext: ['ls'],
  },
  { name: 'Lua', module: 'lua', export: 'lua', ext: ['lua'] },
  { name: 'mIRC', module: 'mirc', export: 'mirc' },
  { name: 'MariaDB SQL', module: 'sql', export: 'mariaDB' },
  {
    name: 'Mathematica',
    module: 'mathematica',
    export: 'mathematica',
    ext: ['m', 'nb', 'wl', 'wls'],
  },
  { name: 'Modelica', module: 'modelica', export: 'modelica', ext: ['mo'] },
  { name: 'MUMPS', module: 'mumps', export: 'mumps', ext: ['mps'] },
  { name: 'MS SQL', module: 'sql', export: 'msSQL' },
  { name: 'mbox', module: 'mbox', export: 'mbox', ext: ['mbox'] },
  { name: 'MySQL', module: 'sql', export: 'mySQL' },
  { name: 'Nginx', module: 'nginx', export: 'nginx' },
  { name: 'NSIS', module: 'nsis', export: 'nsis', ext: ['nsh', 'nsi'] },
  {
    name: 'NTriples',
    module: 'ntriples',
    export: 'ntriples',
    ext: ['nt', 'nq'],
  },
  {
    name: 'Objective-C',
    module: 'clike',
    export: 'objectiveC',
    alias: ['objective-c', 'objc'],
    ext: ['m'],
  },
  {
    name: 'Objective-C++',
    module: 'clike',
    export: 'objectiveCpp',
    alias: ['objective-c++', 'objc++'],
    ext: ['mm'],
  },
  {
    name: 'OCaml',
    module: 'mllike',
    export: 'oCaml',
    ext: ['ml', 'mli', 'mll', 'mly'],
  },
  { name: 'Octave', module: 'octave', export: 'octave', ext: ['m'] },
  { name: 'Oz', module: 'oz', export: 'oz', ext: ['oz'] },
  { name: 'Pascal', module: 'pascal', export: 'pascal', ext: ['p', 'pas'] },
  { name: 'PEG.js', module: 'pegjs', export: 'pegjs', ext: ['jsonld'] },
  { name: 'Perl', module: 'perl', export: 'perl', ext: ['pl', 'pm'] },
  { name: 'Pig', module: 'pig', export: 'pig', ext: ['pig'] },
  { name: 'PLSQL', module: 'sql', export: 'plSQL', ext: ['pls'] },
  { name: 'PostgreSQL', module: 'sql', export: 'pgSQL' },
  {
    name: 'PowerShell',
    module: 'powershell',
    export: 'powerShell',
    ext: ['ps1', 'psd1', 'psm1'],
  },
  {
    name: 'Properties files',
    module: 'properties',
    export: 'properties',
    alias: ['ini', 'properties'],
    ext: ['properties', 'ini', 'in'],
  },
  { name: 'ProtoBuf', module: 'protobuf', export: 'protobuf', ext: ['proto'] },
  {
    name: 'Python',
    module: 'python',
    export: 'python',
    ext: ['BUILD', 'bzl', 'py', 'pyw'],
  },
  { name: 'Puppet', module: 'puppet', export: 'puppet', ext: ['pp'] },
  { name: 'Q', module: 'q', export: 'q', ext: ['q'] },
  { name: 'R', module: 'r', export: 'r', alias: ['rscript'], ext: ['r', 'R'] },
  { name: 'RPM Changes', module: 'rpm', export: 'rpmChanges' },
  { name: 'RPM Spec', module: 'rpm', export: 'rpmSpec', ext: ['spec'] },
  {
    name: 'Ruby',
    module: 'ruby',
    export: 'ruby',
    alias: ['jruby', 'macruby', 'rake', 'rb', 'rbx'],
    ext: ['rb'],
  },
  { name: 'Rust', module: 'rust', export: 'rust', ext: ['rs'] },
  { name: 'SAS', module: 'sas', export: 'sas', ext: ['sas'] },
  { name: 'Sass', module: 'sass', export: 'sass', ext: ['sass'] },
  { name: 'Scala', module: 'clike', export: 'scala', ext: ['scala'] },
  { name: 'Scheme', module: 'scheme', export: 'scheme', ext: ['scm', 'ss'] },
  { name: 'SCSS', module: 'css', export: 'sCSS', ext: ['scss'] },
  {
    name: 'Shell',
    module: 'shell',
    export: 'shell',
    alias: ['bash', 'sh', 'zsh'],
    ext: ['sh', 'ksh', 'bash'],
  },
  { name: 'Sieve', module: 'sieve', export: 'sieve', ext: ['siv', 'sieve'] },
  { name: 'Smalltalk', module: 'smalltalk', export: 'smalltalk', ext: ['st'] },
  { name: 'Solr', module: 'solr', export: 'solr' },
  {
    name: 'SML',
    module: 'mllike',
    export: 'sml',
    ext: ['sml', 'sig', 'fun', 'smackspec'],
  },
  {
    name: 'SPARQL',
    module: 'sparql',
    export: 'sparql',
    alias: ['sparul'],
    ext: ['rq', 'sparql'],
  },
  {
    name: 'Spreadsheet',
    module: 'spreadsheet',
    export: 'spreadsheet',
    alias: ['excel', 'formula'],
  },
  { name: 'SQL', module: 'sql', export: 'sql', ext: ['sql'] },
  { name: 'SQLite', module: 'sql', export: 'sqlite' },
  { name: 'Squirrel', module: 'clike', export: 'squirrel', ext: ['nut'] },
  { name: 'Stylus', module: 'stylus', export: 'stylus', ext: ['styl'] },
  { name: 'Swift', module: 'swift', export: 'swift', ext: ['swift'] },
  { name: 'sTeX', module: 'stex', export: 'stex' },
  {
    name: 'LaTeX',
    module: 'stex',
    export: 'stex',
    alias: ['tex'],
    ext: ['text', 'ltx', 'tex'],
  },
  {
    name: 'SystemVerilog',
    module: 'verilog',
    export: 'verilog',
    ext: ['v', 'sv', 'svh'],
  },
  { name: 'Tcl', module: 'tcl', export: 'tcl', ext: ['tcl'] },
  { name: 'Textile', module: 'textile', export: 'textile', ext: ['textile'] },
  { name: 'TiddlyWiki', module: 'tiddlywiki', export: 'tiddlyWiki' },
  { name: 'Tiki wiki', module: 'tiki', export: 'tiki' },
  { name: 'TOML', module: 'toml', export: 'toml', ext: ['toml'] },
  {
    name: 'troff',
    module: 'troff',
    export: 'troff',
    ext: ['1', '2', '3', '4', '5', '6', '7', '8', '9'],
  },
  {
    name: 'TTCN',
    module: 'ttcn',
    export: 'ttcn',
    ext: ['ttcn', 'ttcn3', 'ttcnpp'],
  },
  { name: 'TTCN_CFG', module: 'ttcn-cfg', export: 'ttcnCfg', ext: ['cfg'] },
  { name: 'Turtle', module: 'turtle', export: 'turtle', ext: ['ttl'] },
  {
    name: 'TypeScript',
    module: 'javascript',
    export: 'typescript',
    alias: ['ts'],
    ext: ['ts'],
  },
  {
    name: 'TypeScript-JSX',
    module: 'javascript',
    export: 'typescript',
    alias: ['tsx'],
    ext: ['tsx'],
  },
  { name: 'Web IDL', module: 'webidl', export: 'webIDL', ext: ['webidl'] },
  { name: 'VB.NET', module: 'vb', export: 'vb', ext: ['vb'] },
  { name: 'VBScript', module: 'vbscript', export: 'vbScript', ext: ['vbs'] },
  { name: 'Velocity', module: 'velocity', export: 'velocity', ext: ['vtl'] },
  { name: 'Verilog', module: 'verilog', export: 'verilog', ext: ['v'] },
  { name: 'VHDL', module: 'vhdl', export: 'vhdl', ext: ['vhd', 'vhdl'] },
  {
    name: 'XML',
    module: 'xml',
    export: 'xml',
    alias: ['rss', 'wsdl', 'xsd'],
    ext: ['xml', 'xsl', 'xsd', 'svg'],
  },
  { name: 'XQuery', module: 'xquery', export: 'xQuery', ext: ['xy', 'xquery'] },
  { name: 'Yacas', module: 'yacas', export: 'yacas', ext: ['ys'] },
  {
    name: 'YAML',
    module: 'yaml',
    export: 'yaml',
    alias: ['yml'],
    ext: ['yaml', 'yml'],
  },
  { name: 'Z80', module: 'z80', export: 'z80', ext: ['z80'] },
  {
    name: 'mscgen',
    module: 'mscgen',
    export: 'mscgen',
    ext: ['mscgen', 'mscin', 'msc'],
  },
  { name: 'xu', module: 'mscgen', export: 'xu', ext: ['xu'] },
  { name: 'msgenny', module: 'mscgen', export: 'msgenny', ext: ['msgenny'] },
  { name: 'WebAssembly', module: 'wast', export: 'wast', ext: ['wat', 'wast'] },
];
